swift/urls.py
from django.urls import path
from swift.views.account import *
from swift.views.curriculum import *
from swift.views.course import *
from swift.views.prompt import *
from swift.views.tool_template import *
from swift.views.template_tool import *

app_name = "appswift"
# views
urlpatterns = [
    # Landing Page
    path("", SignIn.as_view(), name="signin"),
    path("home/", Home.as_view(), name="home"),

    #Login Actions 
    path("signin/", SignIn.as_view(), name="signin"),
    path("forgot-password/", ForgotPassword.as_view(),name="forgot_password"),
    path("signout/", SignOut.as_view(), name="signout"),

    #Curriculum
    path("curriculum/", CurriculumView.as_view(), name="curriculum"),
    path('curriculum/create/', CurriculumCreate.as_view(), name='create_curriculum'),
    path('curriculum/<int:pk>/update/', CurriculumUpdate.as_view(), name='update_curriculum'),
    path('curriculum/<int:pk>/delete/', CurriculumDelete.as_view(), name='delete_curriculum'),


    #Course
    path('course/', CourseView.as_view(), name='course'),
    # path('course/create/', CourseCreate.as_view(), name='create_course'),
    # path('course/<int:pk>/update/', CourseUpdate.as_view(), name='update_course'),
    # path('course/<int:pk>/delete/', CourseDelete.as_view(), name='delete_course'),
    
    #Prompt
    path('prompt/', PromptView.as_view(), name='prompt'),
    path('prompt/create/', PromptCreate.as_view(), name='create_prompt'),
    path('prompt/<int:pk>/update/', PromptUpdate.as_view(), name='update_prompt'),

    #PromptOut
    path('promptout/create/', PromptOutCreate.as_view(), name='create_promptout'),


    #ToolTemplate
    path('tooltemplate/create', ToolTemplateView.as_view(), name='tooltemplate_create'),
    path('tooltemplate/input-details/create',ToolTemplateInputCreateView.as_view(), name='tooltemplate_input_create'),
    
    path('tooltemplate/list',TemplateToolList.as_view(),name='tooltemplate_list'),
    path('tooltemplate/detail/<int:pk>/',TemplateToolDetail.as_view(),name='tooltemplate_form')
    
]

swiftteacher/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import debug_toolbar
from django.conf.urls import handler404, handler500, handler403, handler400

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('swift.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#handler404 = 'hisensehr.views.pageview.custom_page_not_found_view'
#handler403 = 'hisensehr.views.pageview.custom_permission_denied_view'
#handler500 = 'hisensehr.views.pageview.custom_error_view'

swift/forms/account.py
from django import forms
from django.contrib.auth import authenticate
from swift.models import User

#from swift.models import User


class SignInForm(forms.Form):
    email = forms.EmailField(
        label="Email", max_length=225,
        widget=forms.EmailInput( attrs={'class': 'effect', 'placeholder':'Enter your email'} ),
        error_messages={ 'required': 'The email should not be empty' }
    )
    password = forms.CharField(
        label="Password", max_length=50, min_length=1,
        widget= forms.PasswordInput( attrs={'class': 'effect', 'id': 'password', 'placeholder':'Enter the password'} ),
        error_messages={ 'required': 'The password should not be empty', 'min_length': 'The password strength should be 5 characters.' }
    )

swift/forms/course.py
from django import forms
from django.contrib.auth import authenticate
from swift.models import Course

class CourseForm(forms.ModelForm):
    name = forms.CharField( 
        label="Title", max_length=200, required = True,
        widget=forms.TextInput(attrs={'autocomplete':'off'}),
        error_messages={ 'required': 'The name should not be empty' }
    )
    curriculum = forms.CharField(
        label="Curriculum Name", required = True,
        widget=forms.Select(attrs={'autocomplete':'off'}),
        error_messages={ 'required': 'The carriculum should not be empty' }
    )
    
    class Meta:
        model = Course
        fields = ['name','curriculum']

swift/forms/curriculum.py
from django import forms
from django.contrib.auth import authenticate
from swift.models import Curriculum

class CurriculumForm(forms.ModelForm):
    name = forms.CharField( 
        label="Title", max_length=200, required = True,
        widget=forms.TextInput(attrs={'autocomplete':'off'}),
        error_messages={ 'required': 'The name should not be empty' }
    )
    
    class Meta:
        model = Curriculum
        fields = ['name']

swift/forms/prompt.py
from django import forms
from django.contrib.auth import authenticate
from swift.models import Prompt,PromptOutput

class PromptForm(forms.ModelForm):
    name = forms.CharField(
        label='Prompt Name',max_length=150,required=True,
        widget=forms.TextInput(attrs={'autocomplete':'off'}),
        error_messages={ 'required': 'The name should not be empty' }
    )

    class Meta:
        model = Prompt
        fields = ['name']


class PromptOutForm(forms.ModelForm):
    name = forms.CharField(
        label='Name',
        max_length=150,
        required=True,
        widget=forms.TextInput(attrs={'autocomplete': 'off'})
    )
    description = forms.CharField(
        label='Description',
        required=True,
        widget=forms.Textarea(attrs={'rows': 4})
    )

    class Meta:
        model = PromptOutput
        fields = ['prompt', 'name', 'description']

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.text = {
            'name': self.cleaned_data['name'],
            'description': self.cleaned_data['description']
        }
        if commit:
            instance.save()
        return instance

swift/views/account.py
import datetime
from django.views.generic import CreateView,View
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from swift.helper import renderfile
import pdb
import json
from django.http import JsonResponse
from datetime import date
from django.db import transaction
from django.db.models import Q, Prefetch, Count
from django.template.loader import render_to_string
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.template import loader
from django.utils import timezone
from django.core.paginator import Paginator
from django.core.cache import cache
from django.utils.http import url_has_allowed_host_and_scheme
from swift.forms.account import SignInForm
from django.db.models.functions import Concat  
from django.db.models import Value as V
from django.db.models import CharField
from itertools import chain
from operator import attrgetter
#from swift.models import CREATE,  UPDATE, SUCCESS, FAILED, DELETE, READ
from swiftteacher.settings import ACTIVITY_PASSWORD, ALLOWED_IP
#from swift.models import ACTION_TYPES, ACTION_STATUS
from django.core.paginator import *
import calendar
#from hisensehr.tasks import send_email_to_users
from swift.models import User,ToolType
from swift.helper import emailhelper


class SignIn(CreateView):
    template_name = "swift/account/index.html"
    
    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect( reverse('appswift:home' ) )
        
        cache.set('next', request.GET.get('next', None))
        datas = { 'form' : SignInForm() }
        return render(request, self.template_name, datas)

    def post(self, request, *args, **kwargs):
        datas = {}
        form = SignInForm(request.POST)
        if form.is_valid():
            user = authenticate(username=request.POST.get('email'), password=request.POST.get('password'))
            if user is not None and user.is_active:
                login(self.request, user)
                next_url = cache.get('next')
                if next_url:
                    cache.delete('next')
                    if not url_has_allowed_host_and_scheme(url=next_url, allowed_hosts={request.get_host()}, require_https=request.is_secure()):
                        return HttpResponseRedirect(reverse('appswift:home'))
                    else:
                        return HttpResponseRedirect(next_url)
                else:
                    return HttpResponseRedirect(reverse('appswift:home'))
            messages.error(request,"Invalid Login Details")
            return HttpResponseRedirect( reverse('appswift:signin') )
        else:
            email = request.POST.get('email')
            if User.objects.filter(email=email, is_active=False).exists():
                messages.error(request,"Your account is not active")
            else:
                if not request.POST.get('email'):
                    messages.error(request,"Email is required")
                elif not request.POST.get('password'):
                    messages.error(request,"Password is required")
                else:
                    messages.error(request,"Invalid Login Details")
        datas['form'] = form
        return render(request, self.template_name, datas)


class Home(LoginRequiredMixin, CreateView):
    template_name = "swift/account/home.html"
    def get(self, request, *args, **kwargs):
        # if self.request.user.is_authenticated:
        #     return HttpResponseRedirect( reverse('appswift:home' ) )
        cache.set('next', request.GET.get('next', None))
        
        datas = { 'form' : SignInForm() }
        return render(request, self.template_name, datas)
    
class HomeLayout(LoginRequiredMixin,View):
    template_name = "swift/layout/user_base.html"
    def get(self, request, *args, **kwargs):
        tool_types = ToolType.objects.all()
        print('=====',tool_types)

        context ={
            'tool_types':tool_types,
        }
        return render(request, self.template_name,context)



class SignOut(CreateView):
    def get(self, request, *args, **kwargs):
        logout(self.request)
        request.session.flush()
        return HttpResponseRedirect( reverse('appswift:signin') )


class ForgotPassword(View):
    def get(self, request, *args, **kwargs):
        return renderfile(request,'account','forgot_password')
    
    def post(self, request, *args, **kwargs):
        email = request.POST.get('email')
        try:
            user = User.objects.get(email=email)
            scheme = request.is_secure() and "https://" or "http://"
            current_site = get_current_site(request)
            domainlink = scheme + current_site.domain
            mail_subject = 'Swift - Forgot Password'
            template = loader.get_template(
                'hisensehr/email-layout/acc_active_email.html')
            html_temp = template.render({
                'domain': domainlink,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user)}, request)

            content_replace = {"NAME": str(user.first_name).capitalize() + " " + str(user.last_name).capitalize(), "LINK": html_temp}
            if emailhelper(request, mail_subject, 3, content_replace, email,action="forget-password"):
                messages.success(request, 'Reset Password Link Was Sent To Your Email!')
                return HttpResponseRedirect( reverse('appswift:signin') )
            else:
                messages.error(request, "Something went wrong")
                return HttpResponseRedirect( reverse('appswift:forgot_password') )
        except User.DoesNotExist:
            email = request.POST.get('email')
            if not email:
                messages.error(request, "Email is required")
            else:
                messages.error(request, "User not found with this email")
            return renderfile(request, 'account', 'forgot_password')

"""def reset_password_confirm(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        
        if user:
            return renderfile(request, 'account', 'reset_password', {'user': user.id})
        else:
            return renderfile(request, '', '404', {})
    else:
        return renderfile(request, '', '404', {})

def change_password(request):
    userid = request.POST.get('user')
    pwd = request.POST.get('password1')
    cpwd = request.POST.get('password2')
    try:
        user = User.objects.get(pk=userid)
    except User.DoesNotExist:
        user = None
    if not pwd:
        messages.error(request, "Password cannot be empty")
        return renderfile(request, 'account', 'reset_password', {'user': user.id})
    if pwd == cpwd:
        if len(pwd)>=6:
            with transaction.atomic():
                if user:
                    user.set_password(pwd)
                    user.save()
                    # Profile.objects.filter(user=user).update(password_str=pwd)
                    messages.success(request, "Password Changed Successfully")
                    return HttpResponseRedirect( reverse('appswift:signin') )
                else:
                    messages.error(request, "Something went wrong")
                    return renderfile(request, 'account', 'reset_password', {'user': user.id})
        else:
            messages.error(request, "Password must be atleast 8 characters")
            return renderfile(request, 'account', 'reset_password', {'user': user.id})
    else:
        messages.error(request, "New password and confirm password should be same")
        return renderfile(request, 'account', 'reset_password', {'user': user.id})


    
class ActivityLogView(View):
    def get(self, request, *args, **kwargs):
        return renderfile(request,'utils','activity_log')
    
    def post(self, request, *args, **kwargs):
        context = {}
        context['permission_granted'] = False
        #print("--------",ACTIVITY_PASSWORD)
        if ACTIVITY_PASSWORD:
            user_password = request.POST.get('activity_password')
            try:
                #print(ACTIVITY_PASSWORD,"----", user_password)
                if user_password == ACTIVITY_PASSWORD:
                    context['permission_granted'] = True
                    context['action_types'] = ACTION_TYPES
                    context['action_statuses'] = ACTION_STATUS
                    context['employees'] =  User.objects.only('id','first_name','last_name').exclude(is_superuser=True).order_by('first_name')
                else:
                    messages.error(request, "No permission to do the action")
            except Exception as e:
                messages.error(request, "No permission to do the action")
        else:
            messages.error(request, "No permission to do the action")
        return renderfile(request,'utils','activity_log', context)
    
class FetchActivityLogView(View):
    def get(self, request, *args, **kwargs):
        context = {}
        data = {}
        conditions = {}
        page = request.GET.get('page', 1)
        employee = request.GET.get('employee')
        action = request.GET.get('action')
        status = request.GET.get('status')
        from_date = request.GET.get('from_date')

swift/views/course.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, View
from swift.forms.course import CourseForm
from swift.helper import renderfile, is_ajax, LogUserActivity
from swift.models import Course
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.core.paginator import *
from swift.constantvariables import PAGINATION_PERPAGE
from django.shortcuts import get_object_or_404
from swift.models import CREATE,  UPDATE, SUCCESS, FAILED, DELETE, READ
from django.db import transaction
import pdb

class CourseView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        context, response = {},{}
        page = int(request.GET.get('page', 1))
        courses = Course.objects.filter(is_active=True).order_by('-id')
        paginator = Paginator(courses, PAGINATION_PERPAGE)
        try:
            courses = paginator.page(page)
        except PageNotAnInteger:
            courses = paginator.page(1)
        except EmptyPage:
            courses = paginator.page(paginator.num_pages)

        context['courses'], context['current_page'] = courses , page

        if is_ajax(request=request):
            response['status'] = True
            return JsonResponse(response)
        context['form'] = CourseForm
        return renderfile(request,'course','index',context)
    

class CourseCreate(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        data = {}
        form = CourseForm()
        context = {'form':form,'id':0}
        data['status'] = True
        data['title'] = 'Add Course'
        data['template'] = render_to_string('swift/course/course_form.html', context, request=request)
        return JsonResponse(data)

templates/swift/tooltemplate/input_details_form.html
<div class="formbg-inner">
    <div class="edit-curriculum-form">
        
        <div class="field padding-bottom--24 ">
            <label for="name">Place Holder</label> {{form.place_holder}}
            <p class="text-danger mt-2 mb-0">{{ form.place_holder.errors.as_text  }}</p>
        </div>
        <div class="field padding-bottom--24 ">
            <label for="name">Description</label> {{form.description}}
            <p class="text-danger mt-2 mb-0">{{ form.description.errors.as_text  }}</p>
        </div>
        {% if not input_type == 'email' %}
        <div class="field padding-bottom--24">
            <h5>More Validations</h5>
        </div>
        
        <li class="pop-input-items padding-bottom--24">
            <div class="d-flex">
              <div class="pop-input-wrapper max-length">
                <label for="name">maxlength</label>
                {{form.max_length}}
                <p class="text-danger mt-2 mb-0">{{ form.max_length.errors.as_text  }}</p>
              </div>
              <div class="pop-input-wrapper validation-wrapper">
                <label for="name">Max Validation Message </label>
                {{form.max_validation_msg}}
                <p class="text-danger mt-2 mb-0">{{ form.inp_validation_msg1.errors.as_text  }}</p>
              </div>
            </div>
          </li>
          
          <li class="pop-input-items padding-bottom--24">
            <div class="d-flex">
              <div class="pop-input-wrapper max-length">
                <label for="name">minlength</label>
                {{form.min_length}}
                <p class="text-danger mt-2 mb-0">{{ form.min_length.errors.as_text  }}</p>
              </div>
              <div class="pop-input-wrapper validation-wrapper">
                <label for="name">Min Validation Message </label>
                {{form.min_validation_msg}}
                <p class="text-danger mt-2 mb-0">{{ form.inp_validation_msg2.errors.as_text  }}</p>
              </div>
            </div>
          </li>
        {% endif %}
    </div>
  </div>

templates/swift/tooltemplate/template_form.html
{% extends "swift/layout/user_base.html" %}
{% load static %}
{% block body_block %}
<div class="content-inner full-screen">
    <div class="page-block">
        <div class="d-flex justify-content-between">
            <h1 class="page-block-title">{{ tool_template.tool_name }} - {{ tool_template.tool_type }}</h1>
        </div>
        
        <div class="row">
            <div class="col-lg-4">
                <div class="card">
                    <h5 class="card-header">{{ tool_template.tool_type }}</h5>
                    <div class="card-body">
                        <h5 class="card-title">{{ tool_template.tool_name }}</h5>
                        <p class="card-text">{{ tool_template.tool_context }}</p>
                        {% comment %} <a href="{{ tool_template.youtube_link }}" class="btn btn-primary" target="_blank">Open Link</a> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col-lg-6">
                <form method="post">
                        {% csrf_token %}
                        {% for field in forms %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                {{ field }}
                                {% if field.help_text %}
                                    <div class="form-text">{{ field.help_text }}</div>
                                {% endif %}
                                {% for error in field.errors %}
                                    <div class="text-danger">{{ error }}</div>
                                {% endfor %}
                            </div>
                        {% endfor %}
                    <button type="submit" class="btn btn-primary mt-4">Submit</button>
                </form>
            </div>    
        </div>
    </div>
</div>
{% endblock body_block %}

{% block page_script %}
<script src="{% static 'swift/assets/js/tooltemplate.js' %}?v={% now 'd_m_yH:i:s' %}"></script>
<script src="{% static 'swift/assets/js/formset.js' %}?v={% now 'd_m_yH:i:s' %}"></script>

{% endblock page_script %}

templates/swift/tooltemplate/tool_list.html
{% extends "swift/layout/user_base.html" %}
{% load static %}
{% block body_block %}
<div class="content-inner full-screen">
    <div class="page-block">
        <div class="d-flex justify-content-between">
            <h1 class="page-block-title">Tool Template List</h1>
        </div>

        <div class="row" >
                {% for i in tool_types %}
                <div class="col-lg-4 mt-4">
                <div class="card">
                    <h5 class="card-header">{{i.tool_type}}</h5>
                    <div class="card-body">
                      <h5 class="card-title">{{i.tool_name}}</h5>
                      <p class="card-text">{{i.tool_type.description}}</p>
                      <a href="{% url 'appswift:tooltemplate_form' i.id %}" class="btn btn-primary">Open</a>
                    </div>
                </div>
                </div>
                {% endfor %}
        </div>
    </div>
</div>
{% endblock body_block %}

{% block page_script %}
<script src="{% static 'swift/assets/js/tooltemplate.js' %}?v={% now 'd_m_yH:i:s' %}"></script>
<script src="{% static 'swift/assets/js/formset.js' %}?v={% now 'd_m_yH:i:s' %}"></script>

{% endblock page_script %}